language: php
# In order to use PHP 5.4/5.5, use Ubuntu 14 (Trusty) instead of the newer Ubuntu 16 (Xenial)
# https://docs.travis-ci.com/user/languages/php/#php-54x---55x-support-is-available-on-precise-and-trusty-only
dist: trusty
php:
  - "7.1"
  - "5.6"
  - "5.5"
  - "5.4"
install:
  - composer install
script:
  - composer test
notifications:
  irc:
    channels:
      - "chat.freenode.net#jquery-dev"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} %{author}): %{message} - %{build_url}"
